import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  section: {
    padding: 10,
    marginBottom: 20,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
    backgroundColor: '#fff',
    padding: 15,
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#e1e1e1',
  },
  profilePic: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginRight: 15,
    borderWidth: 2,
    borderColor: '#f0f0f0',
  },
  content: {
    flex: 1,
    justifyContent: 'center',
  },
  userName: {
    fontWeight: 'bold',
    fontSize: 18,
    color: '#2a2a2a',
    marginBottom: 5,
  },
  text: {
    fontSize: 16,
    color: '#333333',
    lineHeight: 22,
    marginBottom: 8,
  },
  icons: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  icon: {
    marginHorizontal: 8,
    padding: 5,
    backgroundColor: '#f8f8f8',
    borderRadius: 8,
    shadowColor: '#666',
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 1,
    width: 30,
    height: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  photo: {
    width: '100%',
    height: 200,
    borderRadius: 15,
    marginBottom: 10,
    overflow: 'hidden',
  },
  date: {
    fontSize: 12,
    color: '#666',
    marginTop: 5,
    fontStyle: 'italic',
  },
  headerText: {
    fontWeight: 'bold',
    fontSize: 22,
    color: '#000',
    paddingBottom: 10,
  },
  subHeaderText: {
    fontSize: 18,
    color: '#555',
    paddingBottom: 5,
  },
  separator: {
    height: 1,
    backgroundColor: '#e1e1e1',
    marginVertical: 10,
  },
  button: {
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: '#4CAF50',
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  imageContainer: {
    marginBottom: 15,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#e0e0e0',
  },
  commentContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  commentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
    padding: 10,
  },
  commentTextContainer: {
    flexShrink: 1,
    paddingHorizontal: 10,
  },
  iconsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexShrink: 0,
  },
  commentText: {
    color: '#333',
    fontSize: 14,
    lineHeight: 20,
    marginVertical: 5,
  },
  reactionIcon: {
    width: 25,
    height: 25,
    borderRadius: 12.5,
    backgroundColor: '#e9e9e9',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  reactionText: {
    fontSize: 14,
    color: '#666',
  },
  reactionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 5,
  },
  historyItem: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 15,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  historyText: {
    fontSize: 14,
    color: '#333',
  },
  moreButton: {
    backgroundColor: '#e7e7e7',
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  moreButtonText: {
    fontSize: 14,
    color: '#555',
  },
});
